/**
 * Database Actions Templates
 *
 * This file contains templates for all DATABASE type actions that are automatically
 * created when a new project is initialized. These actions provide pre-configured
 * REST API endpoints for common CRUD operations on project resources.
 */

export interface DatabaseActionTemplate {
  name: string
  description: string
  method: string
  endpoint: string
  urlPattern: 'REAL_ID' | 'PLACEHOLDER' | 'HYBRID'
  required: string[]
  optional: string[]
  results: string[]
  fieldTypes?: Record<string, 'string' | 'number' | 'boolean'>
}

export const DATABASE_ACTIONS_TEMPLATES: DatabaseActionTemplate[] = [
  // ============================================================================
  // PROJECT MEMBERS
  // ============================================================================
  {
    name: 'Get Project Members',
    description: 'List all members of a specific project',
    method: 'GET',
    endpoint: '/members',
    urlPattern: 'REAL_ID',
    required: [],
    optional: ['id', 'userId', 'role'],
    results: ['id', 'userId', 'role', 'createdAt', 'updatedAt'],
  },
  {
    name: 'Add Project Member',
    description: 'Add a new member to the project',
    method: 'POST',
    endpoint: '/members',
    urlPattern: 'REAL_ID',
    required: ['userId'],
    optional: ['role'],
    results: ['id', 'userId', 'role', 'createdAt', 'updatedAt'],
  },
  {
    name: 'Remove Project Member',
    description: 'Remove a member from the project',
    method: 'DELETE',
    endpoint: '/members/{memberId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: ['id', 'userId', 'role', 'createdAt', 'updatedAt'],
  },

  // ============================================================================
  // PRODUCTS
  // ============================================================================
  {
    name: 'Get Project Products',
    description: 'List all products in a specific project',
    method: 'GET',
    endpoint: '/products',
    urlPattern: 'REAL_ID',
    required: [],
    optional: [
      'id',
      'name',
      'description',
      'price',
      'isActive',
      'categoryId',
      'warehouseId',
      'createdById',
    ],
    results: [
      'id',
      'name',
      'description',
      'price',
      'isActive',
      'categoryId',
      'warehouseId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { price: 'number', isActive: 'boolean' },
  },
  {
    name: 'Create Product',
    description: 'Create a new product in the specified project',
    method: 'POST',
    endpoint: '/products',
    urlPattern: 'REAL_ID',
    required: ['name'],
    optional: ['description', 'price', 'categoryId', 'warehouseId', 'isActive'],
    results: [
      'id',
      'name',
      'description',
      'price',
      'isActive',
      'categoryId',
      'warehouseId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { price: 'number', isActive: 'boolean' },
  },
  {
    name: 'Get Product Details',
    description: 'Get detailed information about a specific product',
    method: 'GET',
    endpoint: '/products/{productId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'description',
      'price',
      'isActive',
      'categoryId',
      'warehouseId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { price: 'number', isActive: 'boolean' },
  },
  {
    name: 'Update Product',
    description: 'Update an existing product',
    method: 'PUT',
    endpoint: '/products/{productId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [
      'name',
      'description',
      'price',
      'categoryId',
      'warehouseId',
      'isActive',
    ],
    results: [
      'id',
      'name',
      'description',
      'price',
      'isActive',
      'categoryId',
      'warehouseId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { price: 'number', isActive: 'boolean' },
  },
  {
    name: 'Delete Product',
    description: 'Delete an existing product',
    method: 'DELETE',
    endpoint: '/products/{productId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'description',
      'price',
      'isActive',
      'categoryId',
      'warehouseId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { price: 'number', isActive: 'boolean' },
  },

  // ============================================================================
  // CUSTOMERS
  // ============================================================================
  {
    name: 'Get Project Customers',
    description: 'List all customers in a specific project',
    method: 'GET',
    endpoint: '/customers',
    urlPattern: 'REAL_ID',
    required: [],
    optional: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'location',
      'subscriber',
      'gender',
      'role',
      'website',
      'origin',
      'isActive',
      'createdById',
    ],
    results: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'location',
      'subscriber',
      'gender',
      'role',
      'website',
      'origin',
      'isActive',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { subscriber: 'boolean', isActive: 'boolean' },
  },
  {
    name: 'Create Customer',
    description: 'Create a new customer in the specified project',
    method: 'POST',
    endpoint: '/customers',
    urlPattern: 'REAL_ID',
    required: ['name'],
    optional: [
      'email',
      'phoneNumber',
      'location',
      'subscriber',
      'gender',
      'role',
      'website',
      'origin',
      'isActive',
    ],
    results: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'location',
      'subscriber',
      'gender',
      'role',
      'website',
      'origin',
      'isActive',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { subscriber: 'boolean', isActive: 'boolean' },
  },
  {
    name: 'Get Customer Details',
    description: 'Get detailed information about a specific customer',
    method: 'GET',
    endpoint: '/customers/{customerId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'location',
      'subscriber',
      'gender',
      'role',
      'website',
      'origin',
      'isActive',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { subscriber: 'boolean', isActive: 'boolean' },
  },
  {
    name: 'Update Customer',
    description: 'Update an existing customer',
    method: 'PUT',
    endpoint: '/customers/{customerId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [
      'name',
      'email',
      'phoneNumber',
      'location',
      'subscriber',
      'gender',
      'role',
      'website',
      'isActive',
      'origin',
    ],
    results: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'location',
      'subscriber',
      'gender',
      'role',
      'website',
      'origin',
      'isActive',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { subscriber: 'boolean', isActive: 'boolean' },
  },
  {
    name: 'Delete Customer',
    description: 'Delete an existing customer (with business rule validations)',
    method: 'DELETE',
    endpoint: '/customers/{customerId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'location',
      'subscriber',
      'gender',
      'role',
      'website',
      'origin',
      'isActive',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { subscriber: 'boolean', isActive: 'boolean' },
  },

  // ============================================================================
  // AGENTS
  // ============================================================================
  {
    name: 'Get Project Agents',
    description: 'List all AI agents in a specific project',
    method: 'GET',
    endpoint: '/agents',
    urlPattern: 'REAL_ID',
    required: [],
    optional: [
      'id',
      'name',
      'type',
      'systemInstructions',
      'isActive',
      'createdById',
    ],
    results: [
      'id',
      'name',
      'type',
      'systemInstructions',
      'isActive',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { isActive: 'boolean' },
  },
  {
    name: 'Create Agent',
    description: 'Create a new AI agent in the specified project',
    method: 'POST',
    endpoint: '/agents',
    urlPattern: 'REAL_ID',
    required: ['type'],
    optional: ['name', 'systemInstructions', 'isActive'],
    results: [
      'id',
      'name',
      'type',
      'systemInstructions',
      'isActive',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { isActive: 'boolean' },
  },

  // ============================================================================
  // DEALS
  // ============================================================================
  {
    name: 'Get Project Deals',
    description: 'List all deals in a specific project',
    method: 'GET',
    endpoint: '/deals',
    urlPattern: 'REAL_ID',
    required: [],
    optional: [
      'id',
      'name',
      'dealDate',
      'isActive',
      'isExpired',
      'revenue',
      'customerId',
      'createdById',
    ],
    results: [
      'id',
      'name',
      'dealDate',
      'isActive',
      'isExpired',
      'revenue',
      'customerId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: {
      isActive: 'boolean',
      isExpired: 'boolean',
      revenue: 'number',
    },
  },
  {
    name: 'Create Deal',
    description: 'Create a new deal in the specified project',
    method: 'POST',
    endpoint: '/deals',
    urlPattern: 'REAL_ID',
    required: ['customerId'],
    optional: ['name', 'dealDate', 'isActive', 'isExpired', 'revenue'],
    results: [
      'id',
      'name',
      'dealDate',
      'isActive',
      'isExpired',
      'revenue',
      'customerId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: {
      isActive: 'boolean',
      isExpired: 'boolean',
      revenue: 'number',
    },
  },
  {
    name: 'Get Deal Details',
    description: 'Get detailed information about a specific deal',
    method: 'GET',
    endpoint: '/deals/{dealId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'dealDate',
      'isActive',
      'isExpired',
      'revenue',
      'customerId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: {
      isActive: 'boolean',
      isExpired: 'boolean',
      revenue: 'number',
    },
  },
  {
    name: 'Update Deal',
    description: 'Update an existing deal',
    method: 'PUT',
    endpoint: '/deals/{dealId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [
      'name',
      'dealDate',
      'isActive',
      'isExpired',
      'revenue',
      'customerId',
    ],
    results: [
      'id',
      'name',
      'dealDate',
      'isActive',
      'isExpired',
      'revenue',
      'customerId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: {
      isActive: 'boolean',
      isExpired: 'boolean',
      revenue: 'number',
    },
  },
  {
    name: 'Delete Deal',
    description: 'Delete an existing deal',
    method: 'DELETE',
    endpoint: '/deals/{dealId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'dealDate',
      'isActive',
      'isExpired',
      'revenue',
      'customerId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: {
      isActive: 'boolean',
      isExpired: 'boolean',
      revenue: 'number',
    },
  },

  // ============================================================================
  // CONTACTS
  // ============================================================================
  {
    name: 'Get Project Contacts',
    description: 'List all contacts in a specific project',
    method: 'GET',
    endpoint: '/contacts',
    urlPattern: 'REAL_ID',
    required: [],
    optional: [
      'id',
      'name',
      'companyName',
      'role',
      'email',
      'phoneNumber',
      'website',
      'status',
      'subscriber',
      'gender',
      'location',
      'createdById',
    ],
    results: [
      'id',
      'name',
      'companyName',
      'role',
      'email',
      'phoneNumber',
      'website',
      'status',
      'subscriber',
      'gender',
      'location',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { subscriber: 'boolean' },
  },
  {
    name: 'Create Contact',
    description: 'Create a new contact in the specified project',
    method: 'POST',
    endpoint: '/contacts',
    urlPattern: 'REAL_ID',
    required: ['name', 'email', 'phoneNumber'],
    optional: [
      'companyName',
      'role',
      'website',
      'status',
      'subscriber',
      'gender',
      'location',
    ],
    results: [
      'id',
      'name',
      'companyName',
      'role',
      'email',
      'phoneNumber',
      'website',
      'status',
      'subscriber',
      'gender',
      'location',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { subscriber: 'boolean' },
  },
  {
    name: 'Get Contact Details',
    description: 'Get detailed information about a specific contact',
    method: 'GET',
    endpoint: '/contacts/{contactId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'companyName',
      'role',
      'email',
      'phoneNumber',
      'website',
      'status',
      'subscriber',
      'gender',
      'location',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { subscriber: 'boolean' },
  },
  {
    name: 'Update Contact',
    description: 'Update an existing contact',
    method: 'PUT',
    endpoint: '/contacts/{contactId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [
      'name',
      'companyName',
      'role',
      'email',
      'phoneNumber',
      'website',
      'status',
      'subscriber',
      'gender',
      'location',
    ],
    results: [
      'id',
      'name',
      'companyName',
      'role',
      'email',
      'phoneNumber',
      'website',
      'status',
      'subscriber',
      'gender',
      'location',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { subscriber: 'boolean' },
  },
  {
    name: 'Delete Contact',
    description: 'Delete an existing contact and related leads',
    method: 'DELETE',
    endpoint: '/contacts/{contactId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'companyName',
      'role',
      'email',
      'phoneNumber',
      'website',
      'status',
      'subscriber',
      'gender',
      'location',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { subscriber: 'boolean' },
  },

  // ============================================================================
  // LEADS
  // ============================================================================
  {
    name: 'Get Project Leads',
    description: 'List all leads in a specific project',
    method: 'GET',
    endpoint: '/leads',
    urlPattern: 'REAL_ID',
    required: [],
    optional: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'status',
      'contactId',
      'createdById',
    ],
    results: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'status',
      'contactId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
  },
  {
    name: 'Create Lead',
    description: 'Create a new lead in the specified project',
    method: 'POST',
    endpoint: '/leads',
    urlPattern: 'REAL_ID',
    required: ['name', 'email', 'phoneNumber'],
    optional: ['status', 'contactId'],
    results: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'status',
      'contactId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
  },
  {
    name: 'Get Lead Details',
    description: 'Get detailed information about a specific lead',
    method: 'GET',
    endpoint: '/leads/{leadId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'status',
      'contactId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
  },
  {
    name: 'Update Lead',
    description: 'Update an existing lead',
    method: 'PUT',
    endpoint: '/leads/{leadId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: ['name', 'email', 'phoneNumber', 'status', 'contactId'],
    results: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'status',
      'contactId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
  },
  {
    name: 'Delete Lead',
    description: 'Delete an existing lead',
    method: 'DELETE',
    endpoint: '/leads/{leadId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'email',
      'phoneNumber',
      'status',
      'contactId',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
  },

  // ============================================================================
  // CATEGORIES
  // ============================================================================
  {
    name: 'Get Project Categories',
    description: 'List all categories in a specific project',
    method: 'GET',
    endpoint: '/categories',
    urlPattern: 'REAL_ID',
    required: [],
    optional: [
      'id',
      'name',
      'description',
      'type',
      'isActive',
      'isDefault',
      'createdById',
    ],
    results: [
      'id',
      'name',
      'description',
      'type',
      'isActive',
      'isDefault',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { isActive: 'boolean', isDefault: 'boolean' },
  },
  {
    name: 'Create Category',
    description: 'Create a new category in the specified project',
    method: 'POST',
    endpoint: '/categories',
    urlPattern: 'REAL_ID',
    required: ['name', 'type'],
    optional: ['description', 'isActive'],
    results: [
      'id',
      'name',
      'description',
      'type',
      'isActive',
      'isDefault',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { isActive: 'boolean', isDefault: 'boolean' },
  },
  {
    name: 'Get Category Details',
    description: 'Get detailed information about a specific category',
    method: 'GET',
    endpoint: '/categories/{categoryId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'description',
      'type',
      'isActive',
      'isDefault',
      'createdById',
    ],
    fieldTypes: { isActive: 'boolean', isDefault: 'boolean' },
  },
  {
    name: 'Update Category',
    description: 'Update an existing category',
    method: 'PUT',
    endpoint: '/categories/{categoryId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: ['name', 'description', 'type', 'isActive'],
    results: ['id', 'name', 'description', 'type', 'isActive'],
    fieldTypes: { isActive: 'boolean', isDefault: 'boolean' },
  },
  {
    name: 'Delete Category',
    description:
      'Delete an existing category (cannot delete default categories)',
    method: 'DELETE',
    endpoint: '/categories/{categoryId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'name',
      'description',
      'type',
      'isActive',
      'isDefault',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { isActive: 'boolean', isDefault: 'boolean' },
  },

  // ============================================================================
  // WAREHOUSES
  // ============================================================================
  {
    name: 'Get Project Warehouses',
    description: 'List all warehouses in a specific project',
    method: 'GET',
    endpoint: '/warehouses',
    urlPattern: 'REAL_ID',
    required: [],
    optional: [
      'id',
      'warehouseId',
      'name',
      'description',
      'isActive',
      'isDefault',
      'createdById',
    ],
    results: [
      'id',
      'warehouseId',
      'name',
      'description',
      'isActive',
      'isDefault',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { isActive: 'boolean', isDefault: 'boolean' },
  },
  {
    name: 'Create Warehouse',
    description: 'Create a new warehouse in the specified project',
    method: 'POST',
    endpoint: '/warehouses',
    urlPattern: 'REAL_ID',
    required: ['name'],
    optional: ['description', 'isActive'],
    results: ['name', 'description', 'isActive'],
    fieldTypes: { isActive: 'boolean', isDefault: 'boolean' },
  },
  {
    name: 'Get Warehouse Details',
    description: 'Get detailed information about a specific warehouse',
    method: 'GET',
    endpoint: '/warehouses/{warehouseId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'warehouseId',
      'name',
      'description',
      'isActive',
      'isDefault',
      'createdById',
    ],
    fieldTypes: { isActive: 'boolean', isDefault: 'boolean' },
  },
  {
    name: 'Update Warehouse',
    description: 'Update an existing warehouse',
    method: 'PUT',
    endpoint: '/warehouses/{warehouseId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: ['name', 'description', 'isActive'],
    results: [
      'id',
      'warehouseId',
      'name',
      'description',
      'isActive',
      'isDefault',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { isActive: 'boolean', isDefault: 'boolean' },
  },
  {
    name: 'Delete Warehouse',
    description:
      'Delete an existing warehouse (cannot delete default warehouses)',
    method: 'DELETE',
    endpoint: '/warehouses/{warehouseId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'warehouseId',
      'name',
      'description',
      'isActive',
      'isDefault',
      'createdById',
      'createdAt',
      'updatedAt',
    ],
    fieldTypes: { isActive: 'boolean', isDefault: 'boolean' },
  },

  // ============================================================================
  // PQR
  // ============================================================================
  {
    name: 'Get Project PQRs',
    description: 'List all PQRs in a specific project',
    method: 'GET',
    endpoint: '/pqrs',
    urlPattern: 'REAL_ID',
    required: ['id'],
    optional: [
      'firstName',
      'lastName',
      'phone',
      'email',
      'city',
      'documentType',
      'documentNumber',
      'status',
    ],
    results: [
      'id',
      'firstName',
      'lastName',
      'phone',
      'email',
      'city',
      'documentType',
      'documentNumber',
      'message',
      'status',
      'createdAt',
      'updatedAt',
    ],
  },
  {
    name: 'Create PQR',
    description: 'Create a new PQR in the specified project',
    method: 'POST',
    endpoint: '/pqrs',
    urlPattern: 'REAL_ID',
    required: [
      'firstName',
      'lastName',
      'phone',
      'email',
      'city',
      'documentType',
      'documentNumber',
      'message',
    ],
    optional: ['status'],
    results: [
      'id',
      'firstName',
      'lastName',
      'phone',
      'email',
      'city',
      'documentType',
      'documentNumber',
      'message',
      'status',
      'createdAt',
      'updatedAt',
    ],
  },
  {
    name: 'Get PQR Details',
    description: 'Get detailed information about a specific PQR',
    method: 'GET',
    endpoint: '/pqrs/{pqrId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'firstName',
      'lastName',
      'phone',
      'email',
      'city',
      'documentType',
      'documentNumber',
      'message',
      'status',
      'createdAt',
      'updatedAt',
    ],
  },
  {
    name: 'Update PQR',
    description: 'Update an existing PQR',
    method: 'PUT',
    endpoint: '/pqrs/{pqrId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [
      'firstName',
      'lastName',
      'phone',
      'email',
      'city',
      'documentType',
      'documentNumber',
      'message',
      'status',
    ],
    results: [
      'id',
      'firstName',
      'lastName',
      'phone',
      'email',
      'city',
      'documentType',
      'documentNumber',
      'message',
      'status',
      'createdAt',
      'updatedAt',
    ],
  },
  {
    name: 'Delete PQR',
    description: 'Delete an existing PQR',
    method: 'DELETE',
    endpoint: '/pqrs/{pqrId}',
    urlPattern: 'HYBRID',
    required: ['id'],
    optional: [],
    results: [
      'id',
      'firstName',
      'lastName',
      'phone',
      'email',
      'city',
      'documentType',
      'documentNumber',
      'message',
      'status',
      'createdAt',
      'updatedAt',
    ],
  },
]
